// Stamps lib/buildInfo.ts with the current git short hash + a deploy version
// (timestamp) so the running app can display exactly which build is live.
// Runs automatically before `npm run deploy`. (Temporary cross-check aid.)
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

let hash = 'unknown';
try {
  hash = execSync('git rev-parse --short HEAD').toString().trim();
} catch {
  /* not a git checkout — leave 'unknown' */
}

const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const version = `${now.getFullYear()}.${pad(now.getMonth() + 1)}.${pad(now.getDate())}.${pad(now.getHours())}${pad(now.getMinutes())}`;

const out = `// AUTO-GENERATED by scripts/stamp-build.js at deploy time — do not edit by hand.
export const BUILD_VERSION = '${version}';
export const BUILD_HASH = '${hash}';
export const BUILD_TIME = '${now.toISOString()}';
`;

fs.writeFileSync(path.join(__dirname, '..', 'lib', 'buildInfo.ts'), out);
console.log(`stamped build v${version} · ${hash}`);
